const fs = require('fs');
const path = require('path');

const versionFilePath = path.join(__dirname, '../src/version.ts');

const now = new Date();
const timestamp = now.toISOString();
// Generate a simple short ID (e.g. valid characters from base36 timestamp)
const buildId = 'build-' + Math.floor(now.getTime() / 1000).toString(16);

const content = `// This file is auto-generated by scripts/generateVersion.js
export const BUILD_TIMESTAMP = '${timestamp}';
export const BUILD_ID = '${buildId}';
`;

fs.writeFileSync(versionFilePath, content);

console.log(`Updated ${versionFilePath} with BUILD_ID=${buildId}`);
